import { execFile } from 'node:child_process';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);
const REQUIRED_APIS = [
  'run.googleapis.com',
  'sqladmin.googleapis.com',
  'secretmanager.googleapis.com',
  'artifactregistry.googleapis.com',
  'servicenetworking.googleapis.com',
  'cloudbuild.googleapis.com',
  'compute.googleapis.com',
] as const;

/**
 * Minimal GCP context discovered from the local `gcloud` installation.
 */
export interface GcloudContext {
  projectId?: string;
  region?: string;
  activeAccount?: string;
}

/**
 * Normalized options used to generate transfer-ready GCP configuration files.
 */
export interface GcpSetupOptions {
  projectId: string;
  region: string;
  environment: string;
  appSlug: string;
  resourcePrefix: string;
  artifactRegistryRepositoryId: string;
  databaseName: string;
  apiServiceAccountId: string;
  webServiceAccountId: string;
  apiServiceName: string;
  webServiceName: string;
  migrationJobName: string;
  jwtSecretName: string;
  sendgridSecretName: string;
  emailFromSecretName: string;
  vpcName: string;
  subnetName: string;
  dbIamUser: string;
  cloudSqlInstance: string;
  enableApis: boolean;
  dryRun: boolean;
}

/**
 * Probes the current `gcloud` CLI context so the setup command can reuse the
 * caller's authenticated account, default project, and default region.
 */
export async function detectGcloudContext(): Promise<GcloudContext> {
  const [projectId, region, activeAccount] = await Promise.all([
    safeGcloudValue(['config', 'get-value', 'project']),
    safeGcloudValue(['config', 'get-value', 'compute/region']),
    safeGcloudValue(['auth', 'list', '--filter=status:ACTIVE', '--format=value(account)']),
  ]);

  const context: GcloudContext = {};
  if (projectId) context.projectId = projectId;
  if (region) context.region = region;
  if (activeAccount) context.activeAccount = activeAccount;
  return context;
}

/**
 * Merges CLI overrides with discovered gcloud defaults and derives the Terraform
 * and Cloud Build names used throughout the transfer workflow.
 */
export function resolveSetupOptions(
  argv: readonly string[],
  context: GcloudContext,
): GcpSetupOptions {
  const flags = parseFlags(argv);
  const projectId = flags['project-id'] ?? context.projectId;
  if (!projectId) {
    throw new Error(
      'Missing GCP project id. Pass --project-id <id> or run `gcloud config set project <id>` first.',
    );
  }

  const region = flags.region ?? context.region ?? 'us-central1';
  const environment = flags.environment ?? 'staging';
  const appSlug = sanitizeSlug(flags['app-slug'] ?? 'proctor');
  const resourcePrefix = sanitizeSlug(flags['resource-prefix'] ?? `${appSlug}-${environment}`);
  const artifactRegistryRepositoryId =
    flags['artifact-repo'] ?? `${sanitizeSlug(appSlug)}-images`;
  const databaseName = flags['database-name'] ?? appSlug.replace(/-/g, '_');
  const apiServiceAccountId = flags['api-service-account-id'] ?? `api-${environment}`;
  const webServiceAccountId = flags['web-service-account-id'] ?? `web-${environment}`;
  const apiServiceName = flags['api-service-name'] ?? `api-${environment}`;
  const webServiceName = flags['web-service-name'] ?? `web-${environment}`;
  const migrationJobName = flags['migration-job-name'] ?? `api-migrate-${environment}`;

  return {
    projectId,
    region,
    environment,
    appSlug,
    resourcePrefix,
    artifactRegistryRepositoryId,
    databaseName,
    apiServiceAccountId,
    webServiceAccountId,
    apiServiceName,
    webServiceName,
    migrationJobName,
    jwtSecretName: `${resourcePrefix}-jwt-secret`,
    sendgridSecretName: `${resourcePrefix}-sendgrid-api-key`,
    emailFromSecretName: `${resourcePrefix}-email-from`,
    vpcName: `${resourcePrefix}-vpc`,
    subnetName: `${resourcePrefix}-subnet`,
    dbIamUser: `${apiServiceAccountId}@${projectId}.iam`,
    cloudSqlInstance: `${projectId}:${region}:${resourcePrefix}-pg`,
    enableApis: flags['enable-apis'] === 'true',
    dryRun: flags['dry-run'] === 'true',
  };
}

/**
 * Renders `infra/terraform.tfvars` for the selected target project.
 */
export function renderTerraformTfvars(options: GcpSetupOptions): string {
  return [
    '# Generated by `npm run setup:gcp`.',
    '# Safe to edit locally; this file is gitignored.',
    '',
    `project_id = ${quote(options.projectId)}`,
    `region = ${quote(options.region)}`,
    `environment = ${quote(options.environment)}`,
    '',
    `app_slug = ${quote(options.appSlug)}`,
    `resource_prefix = ${quote(options.resourcePrefix)}`,
    `artifact_registry_repository_id = ${quote(options.artifactRegistryRepositoryId)}`,
    `database_name = ${quote(options.databaseName)}`,
    `api_service_account_id = ${quote(options.apiServiceAccountId)}`,
    `web_service_account_id = ${quote(options.webServiceAccountId)}`,
    `api_service_name = ${quote(options.apiServiceName)}`,
    `web_service_name = ${quote(options.webServiceName)}`,
    `db_iam_user = ${quote(options.dbIamUser)}`,
    '',
  ].join('\n');
}

/**
 * Renders trigger substitutions for Cloud Build in the target project.
 */
export function renderCloudBuildSubstitutions(options: GcpSetupOptions): string {
  return [
    '# Generated by `npm run setup:gcp`.',
    '# Import these values into the Cloud Build trigger for the target project.',
    'substitutions:',
    `  _REGION: ${options.region}`,
    `  _AR_REPO: ${options.artifactRegistryRepositoryId}`,
    `  _ENV: ${options.environment}`,
    `  _DB_NAME: ${options.databaseName}`,
    `  _CLOUD_SQL_INSTANCE: ${options.cloudSqlInstance}`,
    `  _API_SERVICE_ACCOUNT_ID: ${options.apiServiceAccountId}`,
    `  _API_SERVICE_NAME: ${options.apiServiceName}`,
    `  _WEB_SERVICE_NAME: ${options.webServiceName}`,
    `  _MIGRATION_JOB_NAME: ${options.migrationJobName}`,
    `  _VPC_NAME: ${options.vpcName}`,
    `  _SUBNET_NAME: ${options.subnetName}`,
    `  _JWT_SECRET_NAME: ${options.jwtSecretName}`,
    `  _SENDGRID_SECRET_NAME: ${options.sendgridSecretName}`,
    `  _EMAIL_FROM_SECRET_NAME: ${options.emailFromSecretName}`,
    '',
  ].join('\n');
}

/**
 * Human-readable summary shown at the end of setup so the operator knows the
 * next Terraform and Cloud Build commands to run.
 */
export function formatSetupSummary(
  options: GcpSetupOptions,
  context: GcloudContext,
  terraformPath: string,
  cloudBuildPath: string,
): string {
  return [
    '✅ GCP transfer bootstrap ready.',
    '',
    `Project: ${options.projectId}`,
    `Region: ${options.region}`,
    `Environment: ${options.environment}`,
    `Active gcloud account: ${context.activeAccount ?? 'not detected'}`,
    '',
    'Generated files',
    '──────────────',
    `• ${terraformPath}`,
    `• ${cloudBuildPath}`,
    '',
    'Next steps',
    '──────────',
    '1. Review the generated Terraform values and run `terraform init && terraform plan && terraform apply` in infra/.',
    '2. Populate Secret Manager versions for JWT_SECRET, SENDGRID_API_KEY, and EMAIL_FROM.',
    '3. Copy the generated Cloud Build substitutions into the target trigger.',
  ].join('\n');
}

async function main(): Promise<void> {
  if (process.argv.includes('--help')) {
    console.log(formatHelp());
    return;
  }

  const context = await detectGcloudContext();
  const options = resolveSetupOptions(process.argv.slice(2), context);
  const workspaceRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
  const terraformPath = path.join(workspaceRoot, 'infra', 'terraform.tfvars');
  const cloudBuildPath = path.join(workspaceRoot, 'cloudbuild.substitutions.local.yaml');

  if (options.enableApis) {
    await enableRequiredApis(options.projectId);
  }

  const terraformContents = renderTerraformTfvars(options);
  const cloudBuildContents = renderCloudBuildSubstitutions(options);

  if (!options.dryRun) {
    await fs.writeFile(terraformPath, terraformContents, 'utf8');
    await fs.writeFile(cloudBuildPath, cloudBuildContents, 'utf8');
  }

  console.log(
    formatSetupSummary(options, context, relativeToRoot(workspaceRoot, terraformPath), relativeToRoot(workspaceRoot, cloudBuildPath)),
  );

  if (options.dryRun) {
    console.log('\n--- infra/terraform.tfvars ---\n');
    console.log(terraformContents);
    console.log('--- cloudbuild.substitutions.local.yaml ---\n');
    console.log(cloudBuildContents);
  }
}

function parseFlags(argv: readonly string[]): Record<string, string> {
  const values: Record<string, string> = {};
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index]!;
    if (!token.startsWith('--')) {
      continue;
    }

    const [rawKey, inlineValue] = token.slice(2).split('=', 2);
    if (!rawKey) {
      continue;
    }
    const key = rawKey;
    const next = argv[index + 1];
    const value = inlineValue ?? (next && !next.startsWith('--') ? next : 'true');
    if (inlineValue === undefined && next && !next.startsWith('--')) {
      index += 1;
    }
    values[key] = value;
  }
  return values;
}

function sanitizeSlug(value: string): string {
  return value.trim().toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/--+/g, '-');
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function relativeToRoot(workspaceRoot: string, targetPath: string): string {
  return path.relative(workspaceRoot, targetPath) || targetPath;
}

function formatHelp(): string {
  return [
    'Prepare Terraform + Cloud Build configuration for a new GCP project.',
    '',
    'Usage:',
    '  npm run setup:gcp -- --project-id my-project',
    '  npm run setup:gcp -- --project-id my-project --app-slug scheduler --enable-apis',
    '',
    'Flags:',
    '  --project-id <id>               Target GCP project id (defaults to gcloud config)',
    '  --region <region>               Deployment region (defaults to gcloud config or us-central1)',
    '  --environment <name>            Environment suffix, e.g. staging or production',
    '  --app-slug <slug>               Product slug used for generated names',
    '  --resource-prefix <prefix>      Explicit resource prefix override',
    '  --artifact-repo <name>          Artifact Registry repository id',
    '  --database-name <name>          Postgres database name',
    '  --api-service-account-id <id>   API service-account id',
    '  --web-service-account-id <id>   Web service-account id',
    '  --api-service-name <name>       Cloud Run API service name',
    '  --web-service-name <name>       Cloud Run web service name',
    '  --migration-job-name <name>     Cloud Run job name for migrations',
    '  --enable-apis                   Enable all required Google APIs before writing files',
    '  --dry-run                       Print generated files instead of writing them',
  ].join('\n');
}

async function enableRequiredApis(projectId: string): Promise<void> {
  await execFileAsync('gcloud', ['services', 'enable', ...REQUIRED_APIS, `--project=${projectId}`]);
}

async function safeGcloudValue(args: string[]): Promise<string> {
  try {
    const { stdout } = await execFileAsync('gcloud', args, { timeout: 10_000 });
    return stdout.trim();
  } catch {
    return '';
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});

